server:  
  port: ${PORT:0}
  tomcat:
    threads:
      max: 5
spring:  
  application:
    name: sample-customer-identity-ms-mt
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/auth/realms/startupframework/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:    
    root: info
