server:
  port: ${PORT:8080}
spring:
  application:
    name: startup-starter-msa-edge-server-${spring.profiles.active}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
logging:
  level:    
    root: info