server:
  port: ${PORT:8081}
  tomcat:
    threads:
      max: 5
spring:
  application:
    name: startup-msa-admin-server-${spring.profiles.active}
  cloud:
    discovery:
      client:
        simple:
          instances:
            architecture:
              - uri: http://discovery-server:8761
                metadata:
                  management.context-path: /actuator
              - uri: http://config-server:8762
                metadata:
                  management.context-path: /actuator
  boot:
    admin:
      discovery:
        ignored-services: "*msa*"
logging:
  level:
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    org.springframework.boot.autoconfigure.web: INFO
