server:
  port: ${PORT:8081}
  tomcat:
    threads:
      max: 5
spring:
  application:
    name: startup-msa-admin-server-${spring.profiles.active}
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://discovery-server:8761
                metadata:
                  management.context-path: /actuator
              - uri: http://config-server:8762
                metadata:
                  management.context-path: /actuator
logging:
  level:
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    org.springframework.boot.autoconfigure.web: INFO
