server:
  tomcat:
    threads:
      max: 5
spring:
  application:
    name: startup-msa-authorization-server-${spring.profiles.active}
  datasource:
    maxActive: 2
    url: jdbc:postgresql://localhost:5432/postgres-msa-db
    driver-class-name: org.postgresql.Driver
    username: msa
    password: msa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    show-sql: false # No show on production modedmin
    hibernate:
      ddl-auto: update      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:           
      hibernate.event.merge.entity_copy_observer: allow
      #hibernate.jdbc.time_zone: UTC      
      javax.persistence.validation.mode: none
      hibernate.globally_quoted_identifiers: true
  redis:
    host: localhost
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: INFO